name: history-service
version: 0.1
summary: History service to store messages and calls
description: A service to record the messages that are sent and received and the calls that are made in the Ubuntu Touch platform.
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel

apps:
    history-service:
        command: desktop-launch $SNAP/usr/bin/history-daemon
        plugs: [platform]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

#slots:
#    history:
#        interface: history

parts:
    history-service:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off, -DCMAKE_CROSSCOMPILING=On]
        source: .
        build-packages:
            - cmake
            - dh-translations
            - dconf-cli
            - libphonenumber-dev
            - libsqlite3-dev
            - libtelepathy-qt5-dev
            - pkg-config
            - qt5-default
            - qtbase5-dev
            - qtdeclarative5-dev
            - qtpim5-dev
        
        after: [desktop-ubuntu-app-platform]

    environment:
        source: snap
        plugin: dump

